print ("\n\nExercise 3")

aircraft1 = Aircraft()
aircraft2 = Aircraft()
aircraft3 = Aircraft()
aircraft4 = Aircraft()
aircraft5 = Aircraft()
for i in range(0, 10):
    aircraft1.moveRight()
    aircraft1.moveRight()
    aircraft1.moveLeft()
    aircraft1.moveUp()
    aircraft1.moveUp()
    aircraft1.moveDown()

    aircraft2.moveRight()
    aircraft2.moveRight()
    aircraft2.moveUp()
    aircraft2.moveUp()

    aircraft3.moveRight()
    aircraft3.moveLeft()
    aircraft3.moveUp()
    aircraft3.moveUp()
    aircraft3.moveDown()

    aircraft1.moveRight()
    aircraft1.moveRight()
    aircraft1.moveLeft()
    aircraft1.moveUp()
    aircraft1.moveDown()

    aircraft4.moveRight()
    aircraft4.moveLeft()
    aircraft4.moveDown()
    aircraft4.moveDown()

    aircraft5.moveLeft()
    aircraft5.moveLeft()
    aircraft5.moveUp()
    aircraft5.moveUp()
    aircraft5.moveDown()
    aircraft5.moveDown()
    aircraft5.moveDown()
print ("Aircraft1 X -", aircraft1.x, ", Y -", aircraft1.y)
print ("Aircraft2 X -", aircraft2.x, ", Y -", aircraft2.y)
print ("Aircraft3 X -", aircraft3.x, ", Y -", aircraft3.y)
print ("Aircraft4 X -", aircraft4.x, ", Y -", aircraft4.y)
print ("Aircraft5 X -", aircraft5.x, ", Y -", aircraft5.y)
